# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'visionMockup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for visionMockup

pod 'Firebase/Core'
pod 'Firebase/MLVision'
# If using the on-device API:
pod 'Firebase/MLVisionLabelModel'
# pod 'Firebase/MLVisionBarcodeModel'
# pod 'Firebase/MLVisionFaceModel'
# pod 'Firebase/MLVisionTextModel'

end
